### ISSUE TITLE
Downcast error due to missing dtype

### ISSUE THREAD

**Issue by tiagokv** [craffel/theano-tutorial#2]
Hey @craffel,

under **theano.tensor** section in the last print:

```python

print linear_mix(np.array([[1, 2, 3],
                           [4, 5, 6]]), #A
                 np.array([1, 2, 3]) ) #x
```

I believe it's missing a `dtype=theano.config.floatX`, as the other one which is below.

Thanks!

**Comment by craffel** [comment]
Fixed, thanks!
